import { User } from "@/types";

export const MOCK_USERS: User[] = [
    {
        id: "u1", // the demo user
        name: "Rahul Sharma",
        phone: "+91 9876543210",
        email: "rahul@demo.com",
        avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Rahul",
        rating: 4.8,
        totalTrips: 34,
        memberSince: "2023-01-15",
        isVerified: true,
        bio: "Love driving down the western ghats. Music is a must on long trips!",
        preferences: {
            smoking: false,
            pets: true,
            music: "Yes",
            chat: "Chatty",
        },
    },
    {
        id: "u2",
        name: "Priya Desai",
        phone: "+91 6789012345",
        email: "priya@demo.com",
        avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Priya",
        rating: 4.9,
        totalTrips: 112,
        memberSince: "2021-08-01",
        isVerified: true,
        bio: "Safe driver, clean car. Usually travelling between Mumbai and Pune.",
        preferences: {
            smoking: false,
            pets: false,
            music: "Depends",
            chat: "Some chat",
        },
    },
    {
        id: "u3",
        name: "Arjun Verma",
        phone: "+91 5432109876",
        email: "arjun@demo.com",
        avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Arjun",
        rating: 4.5,
        totalTrips: 12,
        memberSince: "2024-02-10",
        isVerified: false,
        bio: "Mostly commute for weekend getaways.",
        preferences: {
            smoking: true,
            pets: false,
            music: "Yes",
            chat: "Silent",
        },
    },
    {
        id: "u4",
        name: "Neha Gupta",
        phone: "+91 7654321098",
        email: "neha@demo.com",
        avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Neha",
        rating: 5.0,
        totalTrips: 8,
        memberSince: "2023-11-20",
        isVerified: true,
        bio: "Always looking for a comfortable ride. I usually travel light.",
        preferences: {
            smoking: false,
            pets: true,
            music: "Yes",
            chat: "Some chat",
        },
    },
    {
        id: "u5",
        name: "Vikram Singh",
        phone: "+91 9898989898",
        email: "vikram@demo.com",
        avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Vikram",
        rating: 4.2,
        totalTrips: 85,
        memberSince: "2022-05-14",
        isVerified: true,
        preferences: {
            smoking: false,
            pets: false,
            music: "Depends",
            chat: "Chatty",
        },
    }
];
